---
- hosts: all
  become: yes
  tasks:
    - user: name=vagrant group=vagrant
    - name: Add source for nodejs
      shell: 'curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -'

    - name: Add source for oracle java 8
      shell: 'add-apt-repository ppa:webupd8team/java -y'

    - name: update apt cache
      apt: update_cache=yes

    - name: Auto accept oralce java license part 1
      shell: '/bin/echo /usr/bin/debconf shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections'

    - name: Auto accept oralce java license part 2
      shell: '/bin/echo /usr/bin/debconf shared/accepted-oracle-license-v1-1 seen true  | /usr/bin/debconf-set-selections'

    - name: install dependency for appium
      apt: name={{ item }} state=present
      with_items:
        - python-software-properties
        - nodejs
        - g++
        - build-essential
        - oracle-java8-installer

    - name: update apt cache
      apt: update_cache=yes

    - name: install appium
      shell: 'npm install -g appium || true'
