---
- hosts: all
  become: yes
  tasks:
    - user: name=vagrant group=vagrant
    - name: Add source for nodejs
      shell: 'curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -'

    - name: Add source for oracle java 8
      shell: 'add-apt-repository ppa:webupd8team/java -y'

    - name: update apt cache
      apt: update_cache=yes

    - name: Auto accept oralce java license part 1
      shell: '/bin/echo /usr/bin/debconf shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections'

    - name: Auto accept oralce java license part 2
      shell: '/bin/echo /usr/bin/debconf shared/accepted-oracle-license-v1-1 seen true  | /usr/bin/debconf-set-selections'

    - name: install dependency for appium
      apt: name={{ item }} state=present
      with_items:
        - python-software-properties
        - nodejs
        - g++
        - build-essential
        - oracle-java8-installer

    - name: update apt cache
      apt: update_cache=yes

    - name: install appium
      shell: 'npm install -g appium || true'

    - name: download android sdk23
      get_url: url=http://dl.google.com/android/android-sdk_r23.0.2-linux.tgz dest=/tmp/android.tgz

    - name: make opt dir for user
      action: file path=/opt/adt/ state=directory mode=0755

    - name: source bashrc
      file: path=/home/vagrant/.bashrc state=touch mode="u=rw,g=r,o=r"

    - name: unpacking android
      action: unarchive copy=no src=/tmp/android.tgz dest=/opt/adt/ creates=/opt/adt/android-sdk-linux

    - name: chown android directory to user vagrant
      file: path=/opt/adt/android-sdk-linux owner=vagrant group=vagrant recurse=yes state=directory

    - name: installing android platform-tools
      shell: echo y | /opt/adt/android-sdk-linux/tools/android update sdk --no-ui --filter platform-tool,sys-img-x86_64-android-23

    - name: Add PATH for android and java
      action: lineinfile dest=/home/vagrant/.bashrc line="{{ item }}"
      with_items:
        - 'export ANDROID_HOME=/opt/adt/android-sdk-linux'
        - 'export JAVA_HOME=/usr/lib/jvm/java-8-oracle'
        - 'export ANDROID_TOOLS=$ANDROID_HOME/tools/'
        - 'export ANDROID_PLATFORM_TOOLS=$ANDROID_HOME/platform-tools/'
        - 'export PATH=$PATH:$ANDROID_TOOLS:$ANDROID_PLATFORM_TOOLS:$JAVA_HOME/bin'
